---

- hosts: provision
  remote_user: hakase
  become: yes
  gather_facts: True
  pre_tasks:
   - setup:
       gather_subset: all

  roles:
    - nginx
    - copy
    - fetch
    - edit
    - replace
    - attr